trigger:
- master

pool:
  vmImage: 'windows-latest'
  demands: maven

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
  
    steps:
    - task: Maven@3
      displayName: 'Maven pom.xml'
      inputs:
        mavenPomFile: pom.xml
    
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
  
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Build.ArtifactsDirectory)'

    - task: AzureRmWebAppDeployment@4
      displayName: 'Azure App Service Deploy: March9WebApp'
      inputs:
        azureSubscription: 'Free Trial (efb08948-01a4-4487-aca4-757f93e436db)'
        WebAppName: March9WebApp
        packageForLinux: '$(Build.ArtifactsDirectory)/**/*.jar'
